version: '3'
services:
  todo:
    image: prologic/todo
    container_name: todo
    restart: always
    ports:
      - 8081:80
    volumes:
      - todo_db:/usr/local/go/src/todo/todo.db
 
volumes:
  todo_db:
